# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e5a92457ff560e289324558c143d14ac8774b57f2ffbd47ec515db4a7479cb274fd9e44a2a6f535c20984e0d2e3bc725fd5308a1879a6cbc54a60e06316d393

test:
  secret_key_base: f04adedd7d389b32730906818453fb940f4b01cd3f67ec84f2b0803d83cef7ff765f1e0d26348e7d1838b3908fb714f399fc811845e159b147969b86ae271272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
